#ifndef DEFINES_H_
#define DEFINES_H_

#include "ap_fixed.h"
#include "ap_int.h"
#include "nnet_utils/nnet_types.h"
#include <cstddef>
#include <cstdio>

// hls-fpga-machine-learning insert numbers
#define N_INPUT_1_1 4
#define N_INPUT_2_1 64
#define N_INPUT_3_1 4
#define N_INPUT_1_2 4
#define N_INPUT_2_2 64
#define N_INPUT_3_2 1
#define OUT_HEIGHT_49 4
#define OUT_WIDTH_49 64
#define N_FILT_49 1
#define N_INPUT_1_2 4
#define N_INPUT_2_2 64
#define N_INPUT_3_2 1
#define OUT_HEIGHT_6 4
#define OUT_WIDTH_6 64
#define N_FILT_6 4
#define OUT_HEIGHT_6 4
#define OUT_WIDTH_6 64
#define N_FILT_6 4
#define OUT_HEIGHT_10 4
#define OUT_WIDTH_10 64
#define N_FILT_10 4
#define OUT_HEIGHT_10 4
#define OUT_WIDTH_10 64
#define N_FILT_10 4
#define OUT_HEIGHT_14 2
#define OUT_WIDTH_14 32
#define N_FILT_14 4
#define N_INPUT_1_17 2
#define N_INPUT_2_17 32
#define N_INPUT_3_17 4
#define OUT_HEIGHT_14 2
#define OUT_WIDTH_14 32
#define N_FILT_14 4
#define OUT_HEIGHT_50 2
#define OUT_WIDTH_50 32
#define N_FILT_50 4
#define OUT_HEIGHT_14 2
#define OUT_WIDTH_14 32
#define N_FILT_14 4
#define OUT_HEIGHT_22 2
#define OUT_WIDTH_22 32
#define N_FILT_22 8
#define OUT_HEIGHT_22 2
#define OUT_WIDTH_22 32
#define N_FILT_22 8
#define OUT_HEIGHT_26 2
#define OUT_WIDTH_26 32
#define N_FILT_26 8
#define OUT_HEIGHT_26 2
#define OUT_WIDTH_26 32
#define N_FILT_26 8
#define OUT_HEIGHT_30 4
#define OUT_WIDTH_30 64
#define N_CHAN_30 8
#define OUT_HEIGHT_31 4
#define OUT_WIDTH_31 64
#define N_FILT_31 4
#define OUT_HEIGHT_31 4
#define OUT_WIDTH_31 64
#define N_FILT_31 4
#define OUT_HEIGHT_51 4
#define OUT_WIDTH_51 64
#define N_FILT_51 4
#define OUT_HEIGHT_31 4
#define OUT_WIDTH_31 64
#define N_FILT_31 4
#define OUT_HEIGHT_38 4
#define OUT_WIDTH_38 64
#define N_FILT_38 4
#define OUT_HEIGHT_38 4
#define OUT_WIDTH_38 64
#define N_FILT_38 4
#define OUT_HEIGHT_42 4
#define OUT_WIDTH_42 64
#define N_FILT_42 4
#define OUT_HEIGHT_42 4
#define OUT_WIDTH_42 64
#define N_FILT_42 4
#define OUT_HEIGHT_52 4
#define OUT_WIDTH_52 64
#define N_FILT_52 1
#define OUT_HEIGHT_46 4
#define OUT_WIDTH_46 64
#define N_FILT_46 1

// hls-fpga-machine-learning insert layer-precision
typedef ap_fixed<8,2,AP_RND,AP_SAT> input_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> input2_t;
typedef ap_fixed<16,6,AP_RND,AP_SAT> model_default_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer49_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> emb1_weight_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> emb1_bias_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer5_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer6_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> convd1_1_weight_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> bias6_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer9_t;
typedef ap_fixed<18,8> relu_1_table_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer10_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> convd1_2_weight_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> bias10_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer13_t;
typedef ap_fixed<18,8> relu_2_table_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer14_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> pool3_weight_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> bias14_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> input17_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer18_t;
typedef ap_fixed<18,8> relu_3_table_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer50_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> emb4_weight_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> emb4_bias_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer21_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer22_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> convb1_1_weight_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> bias22_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer25_t;
typedef ap_fixed<18,8> relu_4_table_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer26_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> convb1_2_weight_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> bias26_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer29_t;
typedef ap_fixed<18,8> relu_5_table_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer30_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer31_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> convu1_1_weight_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> convu1_1_bias_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer34_t;
typedef ap_fixed<18,8> relu_6_table_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer51_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> emb5_weight_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> emb5_bias_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer37_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer38_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> convu1_2_weight_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> bias38_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer41_t;
typedef ap_fixed<18,8> relu_7_table_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer42_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> convu1_3_weight_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> bias42_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer45_t;
typedef ap_fixed<18,8> relu_8_table_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> layer52_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> out_weight_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> out_bias_t;
typedef ap_fixed<8,2,AP_RND,AP_SAT> result_t;
typedef ap_fixed<18,8> relu_9_table_t;

#endif
