// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pointwise_conv_2d_cl_array_array_ap_fixed_8_2_0_0_0_1u_config61_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_data_0_V_dout,
        data_V_data_0_V_empty_n,
        data_V_data_0_V_read,
        data_V_data_1_V_dout,
        data_V_data_1_V_empty_n,
        data_V_data_1_V_read,
        data_V_data_2_V_dout,
        data_V_data_2_V_empty_n,
        data_V_data_2_V_read,
        data_V_data_3_V_dout,
        data_V_data_3_V_empty_n,
        data_V_data_3_V_read,
        res_V_data_V_din,
        res_V_data_V_full_n,
        res_V_data_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state7 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] data_V_data_0_V_dout;
input   data_V_data_0_V_empty_n;
output   data_V_data_0_V_read;
input  [7:0] data_V_data_1_V_dout;
input   data_V_data_1_V_empty_n;
output   data_V_data_1_V_read;
input  [7:0] data_V_data_2_V_dout;
input   data_V_data_2_V_empty_n;
output   data_V_data_2_V_read;
input  [7:0] data_V_data_3_V_dout;
input   data_V_data_3_V_empty_n;
output   data_V_data_3_V_read;
output  [7:0] res_V_data_V_din;
input   res_V_data_V_full_n;
output   res_V_data_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_data_0_V_read;
reg data_V_data_1_V_read;
reg data_V_data_2_V_read;
reg data_V_data_3_V_read;
reg res_V_data_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    data_V_data_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln106_reg_726;
reg    data_V_data_1_V_blk_n;
reg    data_V_data_2_V_blk_n;
reg    data_V_data_3_V_blk_n;
reg    res_V_data_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] icmp_ln106_reg_726_pp0_iter3_reg;
reg   [9:0] indvar_flatten_reg_193;
wire   [0:0] icmp_ln106_fu_301_p2;
wire    ap_block_state2_pp0_stage0_iter0;
wire    io_acc_block_signal_op18;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_state6_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln106_reg_726_pp0_iter1_reg;
reg   [0:0] icmp_ln106_reg_726_pp0_iter2_reg;
wire   [9:0] add_ln106_fu_307_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [7:0] tmp_data_0_V_reg_735;
reg   [7:0] tmp_data_1_V_reg_740;
reg   [7:0] tmp_data_2_V_reg_745;
reg   [7:0] tmp_data_3_V_reg_750;
wire   [13:0] add_ln415_fu_403_p2;
reg   [13:0] add_ln415_reg_755;
wire   [13:0] add_ln415_21_fu_439_p2;
reg   [13:0] add_ln415_21_reg_760;
wire   [13:0] add_ln1192_36_fu_463_p2;
reg   [13:0] add_ln1192_36_reg_765;
wire   [7:0] p_Val2_1_fu_528_p2;
reg   [7:0] p_Val2_1_reg_770;
wire   [0:0] and_ln781_fu_636_p2;
reg   [0:0] and_ln781_reg_776;
wire   [0:0] xor_ln785_6_fu_654_p2;
reg   [0:0] xor_ln785_6_reg_781;
wire   [0:0] and_ln786_fu_666_p2;
reg   [0:0] and_ln786_reg_786;
wire   [0:0] underflow_fu_684_p2;
reg   [0:0] underflow_reg_791;
wire   [0:0] or_ln340_3_fu_690_p2;
reg   [0:0] or_ln340_3_reg_796;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_block_pp0_stage0_01001;
wire  signed [7:0] mul_ln1118_15_fu_204_p1;
wire  signed [7:0] mul_ln1118_fu_205_p1;
wire  signed [7:0] mul_ln1118_16_fu_206_p1;
wire  signed [7:0] mul_ln1118_14_fu_207_p1;
wire   [14:0] mul_ln1118_fu_205_p2;
wire   [12:0] trunc_ln_fu_333_p4;
wire   [13:0] mul_ln1118_14_fu_207_p2;
wire   [11:0] trunc_ln708_s_fu_351_p4;
wire   [14:0] mul_ln1118_15_fu_204_p2;
wire   [12:0] trunc_ln708_35_fu_377_p4;
wire   [0:0] tmp_89_fu_391_p3;
wire   [13:0] zext_ln415_fu_399_p1;
wire  signed [13:0] sext_ln415_32_fu_387_p1;
wire   [14:0] mul_ln1118_16_fu_206_p2;
wire   [12:0] trunc_ln708_36_fu_413_p4;
wire   [0:0] tmp_90_fu_427_p3;
wire   [13:0] zext_ln415_21_fu_435_p1;
wire  signed [13:0] sext_ln415_34_fu_423_p1;
wire  signed [13:0] sext_ln415_fu_361_p1;
wire  signed [13:0] sext_ln1118_32_fu_343_p1;
wire   [0:0] tmp_fu_365_p3;
wire   [7:0] or_ln_fu_451_p3;
wire   [13:0] add_ln1192_fu_445_p2;
wire   [13:0] zext_ln1192_fu_459_p1;
wire  signed [14:0] sext_ln1192_fu_475_p1;
wire  signed [14:0] sext_ln415_33_fu_469_p1;
wire  signed [14:0] sext_ln48_fu_472_p1;
wire   [14:0] acc_0_V_fu_478_p2;
wire   [14:0] acc_0_V_3_fu_484_p2;
wire   [0:0] tmp_93_fu_516_p3;
wire   [7:0] zext_ln415_22_fu_524_p1;
wire   [7:0] p_Val2_s_fu_498_p4;
wire   [0:0] tmp_94_fu_534_p3;
wire   [0:0] p_Result_1_fu_508_p3;
wire   [0:0] xor_ln416_fu_542_p2;
wire   [1:0] tmp_96_fu_562_p4;
wire   [2:0] tmp_97_fu_578_p4;
wire   [0:0] carry_1_fu_548_p2;
wire   [0:0] Range1_all_ones_fu_588_p2;
wire   [0:0] Range1_all_zeros_fu_594_p2;
wire   [0:0] tmp_98_fu_608_p3;
wire   [0:0] Range2_all_ones_fu_572_p2;
wire   [0:0] xor_ln779_fu_616_p2;
wire   [0:0] and_ln779_fu_622_p2;
wire   [0:0] deleted_zeros_fu_600_p3;
wire   [0:0] p_Result_2_fu_554_p3;
wire   [0:0] xor_ln785_5_fu_642_p2;
wire   [0:0] p_Result_s_fu_490_p3;
wire   [0:0] or_ln785_3_fu_648_p2;
wire   [0:0] deleted_ones_fu_628_p3;
wire   [0:0] or_ln786_fu_672_p2;
wire   [0:0] xor_ln786_fu_678_p2;
wire   [0:0] overflow_fu_660_p2;
wire   [0:0] or_ln340_fu_696_p2;
wire   [0:0] or_ln340_24_fu_700_p2;
wire   [7:0] select_ln340_fu_705_p3;
wire   [7:0] select_ln388_fu_711_p3;
wire    ap_CS_fsm_state7;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln106_fu_301_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_193 <= add_ln106_fu_307_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_193 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln106_reg_726_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln1192_36_reg_765 <= add_ln1192_36_fu_463_p2;
        add_ln415_21_reg_760 <= add_ln415_21_fu_439_p2;
        add_ln415_reg_755 <= add_ln415_fu_403_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln106_reg_726_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln781_reg_776 <= and_ln781_fu_636_p2;
        and_ln786_reg_786 <= and_ln786_fu_666_p2;
        or_ln340_3_reg_796 <= or_ln340_3_fu_690_p2;
        p_Val2_1_reg_770 <= p_Val2_1_fu_528_p2;
        underflow_reg_791 <= underflow_fu_684_p2;
        xor_ln785_6_reg_781 <= xor_ln785_6_fu_654_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln106_reg_726 <= icmp_ln106_fu_301_p2;
        icmp_ln106_reg_726_pp0_iter1_reg <= icmp_ln106_reg_726;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln106_reg_726_pp0_iter2_reg <= icmp_ln106_reg_726_pp0_iter1_reg;
        icmp_ln106_reg_726_pp0_iter3_reg <= icmp_ln106_reg_726_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln106_reg_726 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_0_V_reg_735 <= data_V_data_0_V_dout;
        tmp_data_1_V_reg_740 <= data_V_data_1_V_dout;
        tmp_data_2_V_reg_745 <= data_V_data_2_V_dout;
        tmp_data_3_V_reg_750 <= data_V_data_3_V_dout;
    end
end

always @ (*) begin
    if ((icmp_ln106_fu_301_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln106_reg_726 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n;
    end else begin
        data_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln106_reg_726 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_V_data_0_V_read = 1'b1;
    end else begin
        data_V_data_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln106_reg_726 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n;
    end else begin
        data_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln106_reg_726 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_V_data_1_V_read = 1'b1;
    end else begin
        data_V_data_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln106_reg_726 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n;
    end else begin
        data_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln106_reg_726 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_V_data_2_V_read = 1'b1;
    end else begin
        data_V_data_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln106_reg_726 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_3_V_blk_n = data_V_data_3_V_empty_n;
    end else begin
        data_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln106_reg_726 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_V_data_3_V_read = 1'b1;
    end else begin
        data_V_data_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((icmp_ln106_reg_726_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        res_V_data_V_blk_n = res_V_data_V_full_n;
    end else begin
        res_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln106_reg_726_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_V_data_V_write = 1'b1;
    end else begin
        res_V_data_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln106_fu_301_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((icmp_ln106_fu_301_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Range1_all_ones_fu_588_p2 = ((tmp_97_fu_578_p4 == 3'd7) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_594_p2 = ((tmp_97_fu_578_p4 == 3'd0) ? 1'b1 : 1'b0);

assign Range2_all_ones_fu_572_p2 = ((tmp_96_fu_562_p4 == 2'd3) ? 1'b1 : 1'b0);

assign acc_0_V_3_fu_484_p2 = ($signed(sext_ln48_fu_472_p1) + $signed(acc_0_V_fu_478_p2));

assign acc_0_V_fu_478_p2 = ($signed(sext_ln1192_fu_475_p1) + $signed(sext_ln415_33_fu_469_p1));

assign add_ln106_fu_307_p2 = (indvar_flatten_reg_193 + 10'd1);

assign add_ln1192_36_fu_463_p2 = (add_ln1192_fu_445_p2 + zext_ln1192_fu_459_p1);

assign add_ln1192_fu_445_p2 = ($signed(sext_ln415_fu_361_p1) + $signed(sext_ln1118_32_fu_343_p1));

assign add_ln415_21_fu_439_p2 = ($signed(zext_ln415_21_fu_435_p1) + $signed(sext_ln415_34_fu_423_p1));

assign add_ln415_fu_403_p2 = ($signed(zext_ln415_fu_399_p1) + $signed(sext_ln415_32_fu_387_p1));

assign and_ln779_fu_622_p2 = (xor_ln779_fu_616_p2 & Range2_all_ones_fu_572_p2);

assign and_ln781_fu_636_p2 = (carry_1_fu_548_p2 & Range1_all_ones_fu_588_p2);

assign and_ln786_fu_666_p2 = (p_Result_2_fu_554_p3 & deleted_ones_fu_628_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln106_reg_726_pp0_iter3_reg == 1'd0) & (res_V_data_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((icmp_ln106_reg_726 == 1'd0) & (io_acc_block_signal_op18 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln106_reg_726_pp0_iter3_reg == 1'd0) & (res_V_data_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((icmp_ln106_reg_726 == 1'd0) & (io_acc_block_signal_op18 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln106_reg_726_pp0_iter3_reg == 1'd0) & (res_V_data_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((icmp_ln106_reg_726 == 1'd0) & (io_acc_block_signal_op18 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((icmp_ln106_reg_726 == 1'd0) & (io_acc_block_signal_op18 == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter4 = ((icmp_ln106_reg_726_pp0_iter3_reg == 1'd0) & (res_V_data_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign carry_1_fu_548_p2 = (xor_ln416_fu_542_p2 & p_Result_1_fu_508_p3);

assign deleted_ones_fu_628_p3 = ((carry_1_fu_548_p2[0:0] === 1'b1) ? and_ln779_fu_622_p2 : Range1_all_ones_fu_588_p2);

assign deleted_zeros_fu_600_p3 = ((carry_1_fu_548_p2[0:0] === 1'b1) ? Range1_all_ones_fu_588_p2 : Range1_all_zeros_fu_594_p2);

assign icmp_ln106_fu_301_p2 = ((indvar_flatten_reg_193 == 10'd768) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op18 = (data_V_data_3_V_empty_n & data_V_data_2_V_empty_n & data_V_data_1_V_empty_n & data_V_data_0_V_empty_n);

assign mul_ln1118_14_fu_207_p1 = tmp_data_1_V_reg_740;

assign mul_ln1118_14_fu_207_p2 = ($signed({{1'b0}, {14'd21}}) * $signed(mul_ln1118_14_fu_207_p1));

assign mul_ln1118_15_fu_204_p1 = tmp_data_2_V_reg_745;

assign mul_ln1118_15_fu_204_p2 = ($signed({{1'b0}, {15'd47}}) * $signed(mul_ln1118_15_fu_204_p1));

assign mul_ln1118_16_fu_206_p1 = tmp_data_3_V_reg_750;

assign mul_ln1118_16_fu_206_p2 = ($signed(15'd32726) * $signed(mul_ln1118_16_fu_206_p1));

assign mul_ln1118_fu_205_p1 = tmp_data_0_V_reg_735;

assign mul_ln1118_fu_205_p2 = ($signed({{1'b0}, {15'd44}}) * $signed(mul_ln1118_fu_205_p1));

assign or_ln340_24_fu_700_p2 = (or_ln340_fu_696_p2 | and_ln781_reg_776);

assign or_ln340_3_fu_690_p2 = (underflow_fu_684_p2 | overflow_fu_660_p2);

assign or_ln340_fu_696_p2 = (xor_ln785_6_reg_781 | and_ln786_reg_786);

assign or_ln785_3_fu_648_p2 = (xor_ln785_5_fu_642_p2 | p_Result_2_fu_554_p3);

assign or_ln786_fu_672_p2 = (and_ln786_fu_666_p2 | and_ln781_fu_636_p2);

assign or_ln_fu_451_p3 = {{7'd80}, {tmp_fu_365_p3}};

assign overflow_fu_660_p2 = (xor_ln785_6_fu_654_p2 & or_ln785_3_fu_648_p2);

assign p_Result_1_fu_508_p3 = acc_0_V_3_fu_484_p2[32'd11];

assign p_Result_2_fu_554_p3 = p_Val2_1_fu_528_p2[32'd7];

assign p_Result_s_fu_490_p3 = acc_0_V_3_fu_484_p2[32'd14];

assign p_Val2_1_fu_528_p2 = (zext_ln415_22_fu_524_p1 + p_Val2_s_fu_498_p4);

assign p_Val2_s_fu_498_p4 = {{acc_0_V_3_fu_484_p2[11:4]}};

assign res_V_data_V_din = ((or_ln340_24_fu_700_p2[0:0] === 1'b1) ? select_ln340_fu_705_p3 : select_ln388_fu_711_p3);

assign select_ln340_fu_705_p3 = ((or_ln340_3_reg_796[0:0] === 1'b1) ? 8'd127 : p_Val2_1_reg_770);

assign select_ln388_fu_711_p3 = ((underflow_reg_791[0:0] === 1'b1) ? 8'd128 : p_Val2_1_reg_770);

assign sext_ln1118_32_fu_343_p1 = $signed(trunc_ln_fu_333_p4);

assign sext_ln1192_fu_475_p1 = $signed(add_ln1192_36_reg_765);

assign sext_ln415_32_fu_387_p1 = $signed(trunc_ln708_35_fu_377_p4);

assign sext_ln415_33_fu_469_p1 = $signed(add_ln415_reg_755);

assign sext_ln415_34_fu_423_p1 = $signed(trunc_ln708_36_fu_413_p4);

assign sext_ln415_fu_361_p1 = $signed(trunc_ln708_s_fu_351_p4);

assign sext_ln48_fu_472_p1 = $signed(add_ln415_21_reg_760);

assign start_out = real_start;

assign tmp_89_fu_391_p3 = mul_ln1118_15_fu_204_p2[32'd1];

assign tmp_90_fu_427_p3 = mul_ln1118_16_fu_206_p2[32'd1];

assign tmp_93_fu_516_p3 = acc_0_V_3_fu_484_p2[32'd3];

assign tmp_94_fu_534_p3 = p_Val2_1_fu_528_p2[32'd7];

assign tmp_96_fu_562_p4 = {{acc_0_V_3_fu_484_p2[14:13]}};

assign tmp_97_fu_578_p4 = {{acc_0_V_3_fu_484_p2[14:12]}};

assign tmp_98_fu_608_p3 = acc_0_V_3_fu_484_p2[32'd12];

assign tmp_fu_365_p3 = mul_ln1118_14_fu_207_p2[32'd1];

assign trunc_ln708_35_fu_377_p4 = {{mul_ln1118_15_fu_204_p2[14:2]}};

assign trunc_ln708_36_fu_413_p4 = {{mul_ln1118_16_fu_206_p2[14:2]}};

assign trunc_ln708_s_fu_351_p4 = {{mul_ln1118_14_fu_207_p2[13:2]}};

assign trunc_ln_fu_333_p4 = {{mul_ln1118_fu_205_p2[14:2]}};

assign underflow_fu_684_p2 = (xor_ln786_fu_678_p2 & p_Result_s_fu_490_p3);

assign xor_ln416_fu_542_p2 = (tmp_94_fu_534_p3 ^ 1'd1);

assign xor_ln779_fu_616_p2 = (tmp_98_fu_608_p3 ^ 1'd1);

assign xor_ln785_5_fu_642_p2 = (deleted_zeros_fu_600_p3 ^ 1'd1);

assign xor_ln785_6_fu_654_p2 = (p_Result_s_fu_490_p3 ^ 1'd1);

assign xor_ln786_fu_678_p2 = (or_ln786_fu_672_p2 ^ 1'd1);

assign zext_ln1192_fu_459_p1 = or_ln_fu_451_p3;

assign zext_ln415_21_fu_435_p1 = tmp_90_fu_427_p3;

assign zext_ln415_22_fu_524_p1 = tmp_93_fu_516_p3;

assign zext_ln415_fu_399_p1 = tmp_89_fu_391_p3;

endmodule //pointwise_conv_2d_cl_array_array_ap_fixed_8_2_0_0_0_1u_config61_s
